"""
semafide.seal: artifact schema and standalone verifier.

Pre-build scaffold. This package encodes what an artifact must contain and what
a verifier can report about one without overclaiming. It contains no capture
mechanism, because where the witness sits is KC3 and remains open.

It depends on `cryptography` and the standard library only.
"""

from .primitives import (
    OPEN_QUESTIONS,
    Pinning,
    PrimitiveKind,
    PrimitiveRecord,
    Retention,
    canonical_bytes,
    commit,
    merkle_root,
)
from .artifact import (
    AssignmentAnchor,
    Entry,
    EntryKind,
    EvidenceCommitment,
    RederivationRecipe,
    RunSeal,
    SealChain,
    WitnessMode,
    WorkfileBinding,
    chain_identity,
    export_artifact,
    load_artifact,
)
from .anchor import (
    Anchoring,
    AnchorReport,
    Beacon,
    TimeAnchor,
    issue as issue_time_anchor,
    resolve_bounds,
)
from .assignment import (
    AssignmentCheckpoint,
    AssignmentRefusal,
    Issuer as AssignmentIssuer,
    ChainRef,
    Disclosure,
    DisclosureReport,
    assess as assess_disclosure,
    issue as issue_assignment_checkpoint,
)
from .checkpoint import (
    Checkpoint,
    CheckpointRefusal,
    Issuer as CheckpointIssuer,
    issue as issue_checkpoint,
)
from .retention import (
    Holding,
    HoldingReport,
    Provenance,
    RetentionDetermination,
    assess as assess_holding,
    conflicts as retention_conflicts,
    issue as issue_retention_determination,
)
from .log import (
    TransparencyLog,
    TreeHead,
    head_signature_valid,
    heads_consistent,
    sign_head,
    verify_consistency,
    verify_inclusion,
)
from .witness import (
    CONTRADICTION,
    UNRECONCILED,
    Witness,
    WitnessRefusal,
    cosignature_valid,
    count_witnesses,
    equivocation,
    equivocation_holds,
    rebut,
)
from .verifier import (
    BindingLevel,
    Completeness,
    Coverage,
    Finding,
    VerificationReport,
    verify,
)

__all__ = [
    "OPEN_QUESTIONS",
    "Pinning",
    "PrimitiveKind",
    "PrimitiveRecord",
    "Retention",
    "canonical_bytes",
    "commit",
    "merkle_root",
    "Anchoring",
    "AnchorReport",
    "Beacon",
    "TimeAnchor",
    "issue_time_anchor",
    "resolve_bounds",
    "AssignmentAnchor",
    "AssignmentCheckpoint",
    "AssignmentIssuer",
    "AssignmentRefusal",
    "CheckpointIssuer",
    "CheckpointRefusal",
    "ChainRef",
    "Disclosure",
    "DisclosureReport",
    "assess_disclosure",
    "chain_identity",
    "issue_assignment_checkpoint",
    "Entry",
    "EntryKind",
    "EvidenceCommitment",
    "RederivationRecipe",
    "RunSeal",
    "SealChain",
    "WitnessMode",
    "WorkfileBinding",
    "export_artifact",
    "load_artifact",
    "BindingLevel",
    "Checkpoint",
    "Holding",
    "HoldingReport",
    "Provenance",
    "RetentionDetermination",
    "assess_holding",
    "issue_retention_determination",
    "retention_conflicts",
    "TransparencyLog",
    "TreeHead",
    "head_signature_valid",
    "heads_consistent",
    "sign_head",
    "verify_consistency",
    "verify_inclusion",
    "CONTRADICTION",
    "UNRECONCILED",
    "Witness",
    "WitnessRefusal",
    "cosignature_valid",
    "count_witnesses",
    "equivocation",
    "equivocation_holds",
    "rebut",
    "Completeness",
    "Coverage",
    "issue_checkpoint",
    "Finding",
    "VerificationReport",
    "verify",
]
